language: objective-c
osx_image: xcode8.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=TransitionKit.xcworkspace
  - IOS_FRAMEWORK_SCHEME="TransitionKit iOS"
  - MACOS_FRAMEWORK_SCHEME="TransitionKit macOS"
  - secure: GJxuge6KjDfMUa12T6dhCmfDrOKt/QQy00uUHtAfNakQM7+FOJsk46c120GZDHcjtsjme0tgTV4JYEvASMtt/05qvo+GewCXYcPm9a/lfDJHpMa4liFiy8jb5RKkcBPJ5WQXspDuRtS84tm8hdAwWWPvj9Jh2wgYEAy8Id19PPN0CQQiAg7qRtmwgsSDNXxatrSkMffpZyG4z6xBY5o1P/NR4nWs/8zvyMtojPdJU10kNWoklxyfyTyUoBI+3TFd8c+oLfW+Fxf9YpcQNq7dlek0p/cvR05UqBQEfGuEOOxzpreVScCBP6pQqMtvDJmhquyGNVdjLzCwWzbK1bkeNzk4/dapLSIsmINMa+NlxfnjrbagbxOV0ZuN0QVPdixB8XVMAk0fQTAovakrzBVv6BWmG9KN8nKvz5OBYRIWnlgvdsTFxFiFncuGYhg7dDi/STtAedMLzMAbXTHErtEgXLyp3kNMUhjNF4dBjkD4JZf1lyTFEN3EufMmJOkqUZ9i8u2bc0WmxjgjXcxzGJgP9C3ZBYJ/xz7n+FuZtwats2RGjMXHGnu677yjzxl0+dHEwRcNd2jisiZqQyl2xI9/7p072QhHwpgwZWmRCPXd3iLjgv1463bPCtohsdSI8RJxFXpN0wFkk/EXGTXyoU3oQWJrM3J+3QtOqNPfJ3uaVq4=
  matrix:
  - DESTINATION="OS=10.0,name=iPhone 6s Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"
  - DESTINATION="OS=9.0,name=iPad 2"             SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"
  - DESTINATION="arch=x86_64"                    SCHEME="$MACOS_FRAMEWORK_SCHEME"   RUN_TESTS="YES"
script:
- set -o pipefail
- git submodule update --init
- xcodebuild -version

- if [ $RUN_TESTS == "YES" ]; then travis_retry xcodebuild -workspace "$WORKSPACE"
  -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO
  ENABLE_TESTABILITY=YES test; else travis_retry xcodebuild -workspace "$WORKSPACE"
  -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO
  build; fi
- if [ $RUN_TESTS == "YES" ]; then travis_retry xcodebuild -workspace "$WORKSPACE"
  -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO
  ENABLE_TESTABILITY=YES test; else travis_retry xcodebuild -workspace "$WORKSPACE"
  -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO
  build; fi
